// SPEC-0027 R1 — the published receipt artifact: one self-contained HTML page
// per PR. Content parity is the hard bound: every visible string comes from
// renderers that already exist (`renderPrReceiptText` for the rollup,
// `renderReceipt` for each contributor's sliced model) — this module adds only
// fixed structural chrome. No scripts, no external requests; light/dark via a
// single `prefers-color-scheme` media query. Deterministic: same session set,
// byte-identical file (I1), golden-gated (I5).
import type { ReceiptModel } from "../receipt/model.js";
import { renderReceipt } from "../receipt/render.js";
import { renderPrReceiptText, type PrBodyInput } from "./body.js";

export interface ArtifactSession {
  /** Row label — role + display session id, both already on the comment surface. */
  label: string;
  model: ReceiptModel;
  /** SPEC-0031 R3a — per-commit table lines (present only for sliced sessions with anchors). */
  perCommitLines?: string[];
}

export interface ArtifactInput {
  prNumber: number;
  body: PrBodyInput;
  sessions: ArtifactSession[];
  /** SPEC-0031 R1 — session labels that cannot be commit-attributed (labeled bucket, I3). */
  notAttributable?: string[];
  /** SPEC-0031 R3c — the table data as JSON for an inert <template> island. */
  perCommitJson?: string;
}

/** The artifact's file name for a PR — shared by the publisher and the comment link (R3). */
export function artifactFileName(prNumber: number): string {
  return `pr-${prNumber}.html`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const STYLE = `:root{--paper:#FAF7F1;--ink:#23262E;--muted:#8B8578;--ground:#EFEAE0}
@media (prefers-color-scheme:dark){:root{--paper:#2D3039;--ink:#E8E6E1;--muted:#9A958C;--ground:#262932}}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:ui-monospace,'SF Mono',Menlo,Consolas,monospace}
main{max-width:56ch;margin:0 auto;padding:40px 16px 72px}
h1{font-size:15px;font-weight:600;letter-spacing:.14em;text-align:center;margin:0 0 4px}
p.sub{font-size:12px;color:var(--muted);text-align:center;margin:0 0 28px}
h2{font-size:12px;font-weight:600;color:var(--muted);margin:32px 0 8px;overflow-wrap:anywhere}
section>div{background:var(--paper);padding:16px 0;overflow-x:auto}
pre{font-family:inherit;font-size:12.5px;line-height:1.6;margin:0;padding:0 14px;width:50ch}
footer{font-size:11px;color:var(--muted);text-align:center;margin-top:36px}\ndiv.pc{background:var(--paper);padding:12px 0 0;overflow-x:auto}\ndiv.pc pre{font-size:11.5px;color:var(--muted)}`;

/**
 * Render the complete artifact page. Pure string assembly over renderer
 * outputs — the only non-renderer strings are the fixed chrome below and the
 * PR number the file is named for.
 */
export function renderPrArtifactHtml(input: ArtifactInput): string {
  const rollup = escapeHtml(renderPrReceiptText(input.body));
  const sections = input.sessions
    .map((s) => {
      const perCommit =
        s.perCommitLines !== undefined && s.perCommitLines.length > 0
          ? `<div class="pc"><pre>${escapeHtml(s.perCommitLines.join("\n"))}</pre></div>`
          : "";
      return `<section><h2>${escapeHtml(s.label)}</h2>${perCommit}<div><pre>${escapeHtml(
        renderReceipt(s.model, { color: false }),
      )}</pre></div></section>`;
    })
    .join("\n");
  const bucket =
    input.notAttributable !== undefined && input.notAttributable.length > 0
      ? `<section><h2>not commit-attributable</h2><div><pre>${escapeHtml(input.notAttributable.join("\n"))}</pre></div></section>`
      : "";
  // JSON-safe island: unicode-escape &,<,> inside the JSON text so the raw
  // template content is simultaneously valid JSON and unable to close the
  // template or open a script (a hostile commit subject can't break out).
  const island =
    input.perCommitJson !== undefined
      ? `<template id="per-commit">${input.perCommitJson.replace(/&/g, "\\u0026").replace(/</g, "\\u003c").replace(/>/g, "\\u003e")}</template>`
      : "";
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>aireceipts · PR #${input.prNumber}</title>`,
    `<style>${STYLE}</style>`,
    "</head>",
    "<body>",
    "<main>",
    "<h1>AIRECEIPTS</h1>",
    `<p class="sub">receipt artifact · PR #${input.prNumber}</p>`,
    `<section><div><pre>${rollup}</pre></div></section>`,
    sections,
    bucket,
    island,
    "<footer>aireceipts · local · generated by aireceipts pr --post --artifact</footer>",
    "</main>",
    "</body>",
    "</html>",
    "",
  ]
    .filter((part) => part !== "")
    .join("\n");
}
