// SPEC-0027 R1 — the published receipt artifact: one self-contained HTML page
// per PR. Content parity is the hard bound: every visible string comes from
// renderers that already exist (`renderPrReceiptText` for the rollup,
// `renderReceipt` for each contributor's sliced model) — this module adds only
// fixed structural chrome. No scripts, no external requests; light/dark via a
// single `prefers-color-scheme` media query. Deterministic: same session set,
// byte-identical file (I1), golden-gated (I5).
import type { ReceiptModel } from "../receipt/model.js";
import { renderReceipt } from "../receipt/render.js";
import { renderPrReceiptText, type PrBodyInput } from "./body.js";

export interface ArtifactSession {
  /** Row label — role + display session id, both already on the comment surface. */
  label: string;
  model: ReceiptModel;
}

export interface ArtifactInput {
  prNumber: number;
  body: PrBodyInput;
  sessions: ArtifactSession[];
}

/** The artifact's file name for a PR — shared by the publisher and the comment link (R3). */
export function artifactFileName(prNumber: number): string {
  return `pr-${prNumber}.html`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const STYLE = `:root{--paper:#FAF7F1;--ink:#23262E;--muted:#8B8578;--ground:#EFEAE0}
@media (prefers-color-scheme:dark){:root{--paper:#2D3039;--ink:#E8E6E1;--muted:#9A958C;--ground:#262932}}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:ui-monospace,'SF Mono',Menlo,Consolas,monospace}
main{max-width:56ch;margin:0 auto;padding:40px 16px 72px}
h1{font-size:15px;font-weight:600;letter-spacing:.14em;text-align:center;margin:0 0 4px}
p.sub{font-size:12px;color:var(--muted);text-align:center;margin:0 0 28px}
h2{font-size:12px;font-weight:600;color:var(--muted);margin:32px 0 8px;overflow-wrap:anywhere}
section>div{background:var(--paper);padding:16px 0;overflow-x:auto}
pre{font-family:inherit;font-size:12.5px;line-height:1.6;margin:0;padding:0 14px;width:50ch}
footer{font-size:11px;color:var(--muted);text-align:center;margin-top:36px}`;

/**
 * Render the complete artifact page. Pure string assembly over renderer
 * outputs — the only non-renderer strings are the fixed chrome below and the
 * PR number the file is named for.
 */
export function renderPrArtifactHtml(input: ArtifactInput): string {
  const rollup = escapeHtml(renderPrReceiptText(input.body));
  const sections = input.sessions
    .map(
      (s) =>
        `<section><h2>${escapeHtml(s.label)}</h2><div><pre>${escapeHtml(
          renderReceipt(s.model, { color: false }),
        )}</pre></div></section>`,
    )
    .join("\n");
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>aireceipts · PR #${input.prNumber}</title>`,
    `<style>${STYLE}</style>`,
    "</head>",
    "<body>",
    "<main>",
    "<h1>AIRECEIPTS</h1>",
    `<p class="sub">receipt artifact · PR #${input.prNumber}</p>`,
    `<section><div><pre>${rollup}</pre></div></section>`,
    sections,
    "<footer>aireceipts · local · generated by aireceipts pr --post --artifact</footer>",
    "</main>",
    "</body>",
    "</html>",
    "",
  ].join("\n");
}
