/** Canonical open-source identity for receipt provenance surfaces. */
export const REPOSITORY_URL = "https://github.com/anandgupta42/receipts";
export const REPOSITORY_DISPLAY = "github.com/anandgupta42/receipts";
export const INSTALL_FOOTER_TEXT = "aireceipts · local · npx aireceipts-cli";
export const PR_ATTRIBUTION_LINE = `Generated by [aireceipts on GitHub](${REPOSITORY_URL}) · install: \`npx aireceipts-cli\``;
