// SPEC-0021 R4: every pixel and character of receipt output on the landing page
// is generated BY the product from committed fixtures — never hand-drawn, never a
// mockup — so the site can never drift from what the tool actually renders. Run
// with a frozen env (NO_COLOR=1 TZ=UTC LANG=C) exactly like goldens.mts; the CI
// asset-parity check re-runs this and byte-compares.
//
//   npx tsx scripts/site-assets.mts            # write assets + print minis
//   npx tsx scripts/site-assets.mts --verify   # fail if the PNG drifted
import { loadById } from "../src/index.js";
import type { AgentSource } from "../src/index.js";
import { buildReceiptModel } from "../src/receipt/model.js";
import { renderReceiptSvg } from "../src/receipt/svg.js";
import { rasterizeSvgToPng } from "../src/receipt/png.js";
import { renderCompare } from "../src/receipt/compare.js";
import { renderStatusline } from "../src/receipt/mini.js";
import { renderWeek } from "../src/receipt/week.js";
import { assembleWeekDigest, windowBounds } from "../src/aggregate/week.js";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";

const CC = "claude-code" as AgentSource;
const LOOP = "test/fixtures/claude-code/loop-bash-5x.jsonl";
const CLEAN = "test/fixtures/claude-code/clean-multi-tool-2-models.jsonl";
const verify = process.argv.includes("--verify");

async function modelFor(path: string) {
  const session = await loadById(CC, path);
  if (!session) {
    console.error(`site-assets: failed to load ${path}`);
    process.exit(1);
  }
  return buildReceiptModel(session);
}

const loop = await modelFor(LOOP);
const clean = await modelFor(CLEAN);

// Band 2 — the hero: a real session with the waste line firing, dark theme, PNG.
mkdirSync("site/assets", { recursive: true });
const heroPng = rasterizeSvgToPng(renderReceiptSvg(loop, { theme: "dark" }));
const heroPath = "site/assets/hero-receipt.png";
if (verify) {
  if (!existsSync(heroPath) || !readFileSync(heroPath).equals(heroPng)) {
    console.error(`site-assets: DRIFT in ${heroPath} (run without --verify)`);
    process.exit(1);
  }
  console.log("site-assets: hero PNG byte-identical.");
} else {
  writeFileSync(heroPath, heroPng);
  console.log(`site-assets: wrote ${heroPath} (${heroPng.length} bytes)`);
}

// Band 5 — the three text minis, real verbatim output for the page's <pre> blocks.
// A deterministic week digest: both fixtures fall inside one fixed current window,
// the prior window is empty (no synthetic history invented).
const now = Date.UTC(2026, 5, 20, 12, 0, 0);
const digest = await assembleWeekDigest(windowBounds(now), [
  (await loadById(CC, LOOP))!,
  (await loadById(CC, CLEAN))!,
], [], { sinceOverride: false, byProject: false });

const compareText = renderCompare(clean, loop, { color: false, termWidth: 120 });
const weekText = renderWeek(digest, { color: false });
const statuslineText = renderStatusline(loop);

const banner = (t: string) => `\n===== ${t} =====\n`;
process.stdout.write(banner("COMPARE (clean vs loop, side-by-side)") + compareText + "\n");
process.stdout.write(banner("WEEK DIGEST") + weekText + "\n");
process.stdout.write(banner("STATUSLINE") + statuslineText + "\n");

if (process.env.SITE_ASSETS_DUMP) {
  writeFileSync(`${process.env.SITE_ASSETS_DUMP}/compare.txt`, compareText);
  writeFileSync(`${process.env.SITE_ASSETS_DUMP}/week.txt`, weekText);
  writeFileSync(`${process.env.SITE_ASSETS_DUMP}/statusline.txt`, statuslineText);
}
