// SPEC-0027 R1 — the artifact page: self-contained (no fetches, no scripts),
// one prefers-color-scheme block, content parity with the renderers it wraps,
// deterministic bytes. The committed golden (goldens/html/pr-artifact.html)
// is the byte gate; these tests assert the properties.
import { describe, expect, it } from "vitest";
import { loadById } from "../../src/parse/load.js";
import { buildReceiptModel } from "../../src/receipt/model.js";
import { renderReceipt } from "../../src/receipt/render.js";
import { renderPrReceiptText, type ContributorView } from "../../src/pr/body.js";
import { artifactFileName, renderPrArtifactHtml, type ArtifactInput } from "../../src/pr/html.js";
import { SAMOSA_URL } from "../../src/pr/publish.js";
import { REPOSITORY_URL } from "../../src/receipt/branding.js";

const FIXTURE = "test/fixtures/claude-code/clean-multi-tool-2-models.jsonl";

async function makeInput(): Promise<ArtifactInput> {
  const session = (await loadById("claude-code", FIXTURE))!;
  const model = await buildReceiptModel(session);
  const view: ContributorView = {
    role: "builder",
    sessionId: "sess-a",
    slice: { kind: "full", startTurn: 0, endTurn: 0, turnCount: 1, label: "entire session (slice unavailable)" },
    modelMix: model.modelMix,
    usd: model.totalUsd,
    tokens: model.totalTokens,
    subagents: [],
  };
  return { prNumber: 7, body: { contributors: [view], excludedCount: 0 }, sessions: [{ label: "builder · sess-a", model }] };
}

describe("SPEC-0027 R1 artifact page", () => {
  function hrefs(html: string): string[] {
    return [...html.matchAll(/<a href="([^"]+)"/g)].map((match) => match[1]);
  }

  function expectNoRemoteSubresources(html: string): void {
    expect(html).not.toContain("<script");
    expect(html).not.toContain("<link");
    expect(html).not.toContain("<img");
    expect(html).not.toContain("<iframe");
    expect(html).not.toContain("@import");
    expect(html).not.toContain("@font-face");
    expect(html).not.toContain("url(");
  }

  it("is self-contained by default with only the intentional source-and-install anchor", async () => {
    const html = renderPrArtifactHtml(await makeInput());
    expect(hrefs(html)).toEqual([REPOSITORY_URL]);
    expect(html).toContain(`<a href="${REPOSITORY_URL}">source & install</a>`);
    expect(html).not.toContain("buy me a samosa");
    expectNoRemoteSubresources(html);
  });

  it("with --samosa, allows the source-and-install and intentional tip anchors only", async () => {
    const html = renderPrArtifactHtml({ ...(await makeInput()), samosa: true });
    expect(hrefs(html)).toEqual([REPOSITORY_URL, SAMOSA_URL]);
    expect(html).toContain(`<a href="${SAMOSA_URL}">buy me a samosa</a>`);
    expectNoRemoteSubresources(html);
  });

  it("defines both palettes inline behind exactly one prefers-color-scheme query", async () => {
    const html = renderPrArtifactHtml(await makeInput());
    expect(html.match(/prefers-color-scheme/g)).toHaveLength(1);
  });

  it("renders the rollup and each session through the existing renderers (content parity)", async () => {
    const input = await makeInput();
    const html = renderPrArtifactHtml(input);
    const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    expect(html).toContain(esc(renderPrReceiptText(input.body)));
    expect(html).toContain(esc(renderReceipt(input.sessions[0].model, { color: false })));
  });

  it("contains NOTHING beyond renderer output and the enumerated fixed chrome (absence side)", async () => {
    const input = await makeInput();
    const html = renderPrArtifactHtml(input);
    // Strip tags and style, unescape, subtract every renderer-produced line.
    const text = html
      .replace(/<style>[\s\S]*?<\/style>/, "")
      .replace(/<[^>]+>/g, "\n")
      .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
    const rendererLines = new Set([
      ...renderPrReceiptText(input.body).split("\n"),
      ...renderReceipt(input.sessions[0].model, { color: false }).split("\n"),
      ...input.sessions.map((s) => s.label),
    ].map((l) => l.trim()));
    const CHROME = new Set(["AIRECEIPTS", `receipt artifact · PR #${input.prNumber}`,
      "aireceipts · local · generated by aireceipts pr --post --artifact",
      "source & install",
      "buy me a samosa",
      `aireceipts · PR #${input.prNumber}`]);
    for (const line of text.split("\n").map((l) => l.trim()).filter((l) => l !== "")) {
      expect(rendererLines.has(line) || CHROME.has(line), `unexpected string in artifact: "${line}"`).toBe(true);
    }
  });

  it("is byte-deterministic across renders (I1)", async () => {
    const input = await makeInput();
    expect(renderPrArtifactHtml(input)).toBe(renderPrArtifactHtml(await makeInput()));
  });

  it("names the file from the PR number — shared by publisher and link", () => {
    expect(artifactFileName(61)).toBe("pr-61.html");
  });
});
